<?php

module_load_include('inc', basename(__DIR__), basename(__DIR__) . '.classes');
module_load_include('inc', basename(__DIR__), basename(__DIR__) . '.callbacks');

/**
 * Implements hook_menu().
 */
function nytech_api_menu() {
  $items = [];

  $item = new NyTechMenu(__DIR__);
  $item->path('api/v1/test/%');
  $item->page_callback('api_test');
  $item->page_arguments([3]);
  $item->access_callback(true);
  $item->json_output();
  $items = $item->item($items);

  $item = new NyTechMenu(__DIR__);
  $item->path('api/v1/account');
  $item->page_callback('api_account');
  $item->access_callback(true);
  $item->json_output();
  $items = $item->item($items);

  return $items;
}


